spring.application.name=taskremainder


# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/taskremainder
spring.datasource.username=root
spring.datasource.password=akshitha

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Server port
server.port=8081
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tunikiakshitha55@gmail.com
spring.mail.password=akshitha#15
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
